// Generated by CoffeeScript 1.7.1
var SiderophoreProducer, arena, i, model, _i;

model = require('./model');

SiderophoreProducer = model;

arena = new model.Arena({
  minX: 0,
  maxX: 500,
  minY: 0,
  maxY: 500
});

for (i = _i = 1; _i <= 5; i = ++_i) {
  arena.addSeeker({
    type: "E-coli",
    canEat: ["glucose", "bound-siderophore"]
  });
  arena.addObject(new SiderophoreProducer({}));
}

//# sourceMappingURL=test.map
